[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "calories_tracker"
version = "0.1.0"
description = "Simple app to track calories. Developed at Universtitat Leipzig"
authors = [{ name = "tucamar", email = "xxtucamarxx@gmail.com" }]
dependencies = [
    "pandas",
    "fzf-wrapper"
    ]
readme = "README.md"

[tool.setuptools]
packages = ["calories_tracker"]
